### ISSUE TITLE
Timeloop command line and configuration used in the paper

### ISSUE THREAD

**Issue by vmiheer** [ucb-bar/cosa#3]
Hi I was wondering if you can post the timeloop-mapper yaml and command line you used for the paper. I installed the timeloop as you suggested in the readme and using simba arch in the repository along with resnet workloads in configs. I am adding mapper config file to explicitly set `num-threads` but letting everything else be default. But mapper is able to use only 1 processors in many cases.
I was wondering if you can help with this.

**Comment by hqjenny** [comment]
Hi, 

Sorry for the late response. Below is the mapper script we used to optimize for latency. 
It is odd since in our case, this script launches the max # of threads of the server which is 32. 
We will double check in our run also. 
 
```
mapper:
  algorithm: hybrid
  optimization-metrics: [delay, last-level-accesses]

  victory-condition: 500
  #search-size: 500
  timeout: 0
#  live-status: True
```
